// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxhw9BUEYjmlo2jsIduuoRdHR8HPP3UEM',
    appId: '1:930257398546:web:d5e776e877db7cc15261cb',
    messagingSenderId: '930257398546',
    projectId: 'examen-machucabarbara-ca001',
    authDomain: 'examen-machucabarbara-ca001.firebaseapp.com',
    storageBucket: 'examen-machucabarbara-ca001.appspot.com',
    measurementId: 'G-X9WM9CSWHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxVF5SFIRG6iyB3Tiwn9FPHxR_1vg97U0',
    appId: '1:930257398546:android:faa706c62c0746785261cb',
    messagingSenderId: '930257398546',
    projectId: 'examen-machucabarbara-ca001',
    storageBucket: 'examen-machucabarbara-ca001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCODhGI0u7_g2W3FphKJflar2OcirxBXHk',
    appId: '1:930257398546:ios:34cac2f880de37aa5261cb',
    messagingSenderId: '930257398546',
    projectId: 'examen-machucabarbara-ca001',
    storageBucket: 'examen-machucabarbara-ca001.appspot.com',
    iosBundleId: 'com.example.examenMachuca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCODhGI0u7_g2W3FphKJflar2OcirxBXHk',
    appId: '1:930257398546:ios:bdfaee6f60d6faf85261cb',
    messagingSenderId: '930257398546',
    projectId: 'examen-machucabarbara-ca001',
    storageBucket: 'examen-machucabarbara-ca001.appspot.com',
    iosBundleId: 'com.example.examenMachuca.RunnerTests',
  );
}
